import { Images, Icons } from '../assets';

export const videoData = [
    {
        video: 'https://www.w3schools.com/html/mov_bbb.mp4', 
        postProfile: Icons.profile,
        title: 'Virat Kohli',
        followers: '785 Followers',
        likes: '245k',
        isLike: false,
    },
    {
        video: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4',
        postProfile: Icons.profile,
        title: 'Hritik Roshan',
        followers: '785 Followers',
        likes: '656k',
        isLike: false,
    },
    {
        video: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        postProfile: Icons.profile,
        title: 'Virat Kohli',
        followers: '785 Followers',
        likes: '243k',
        isLike: false,
    },
    {
        video: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        postProfile: Icons.profile,
        title: 'Rohit Sharma',
        followers: '785 Followers',
        likes: '876k',
        isLike: false,
    },
    {
        video: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        postProfile: Icons.profile,
        title: 'Lionel Messi',
        followers: '785 Followers',
        likes: '1.2M',
        isLike: false,
    },
    {
        video: 'https://filesamples.com/samples/video/mp4/sample_640x360.mp4',
        postProfile: Icons.profile,
        title: 'MS Dhoni',
        followers: '785 Followers',
        likes: '56k',
        isLike: false,
    },
    {
        video: 'https://filesamples.com/samples/video/mp4/sample_960x400_ocean_with_audio.mp4',
        postProfile: Icons.profile,
        title: 'Cillian Murphy',
        followers: '785 Followers',
        likes: '90k',
        isLike: false,
    },
    {
        video: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        postProfile: Icons.profile,
        title: 'Henry Cavill',
        followers: '785 Followers',
        likes: '25k',
        isLike: false,
    },
    {
        video: 'https://filesamples.com/samples/video/mp4/sample_1280x720.mp4',
        postProfile: Icons.profile,
        title: 'Sachin Tendulkar',
        followers: '785 Followers',
        likes: '76k',
        isLike: false,
    },
];
