import {  Icons, videos } from '../assets';

export const videoData = [
    {
        video:videos.video1,
        postProfile: Icons.profile,
        title: 'Virat Kohli',
        followers: '785 Followers',
        likes: '245k',
        isLike: false,
    },
    {
        video:videos.video2,
        postProfile: Icons.profile,
        title: 'Hritik Roshan',
        followers: '785 Followers',
        likes: '656k',
        isLike: false,
    },
    {
        video:videos.video3,
        postProfile: Icons.profile,
        title: 'Virat Kohli',
        followers: '785 Followers',
        likes: '243k',
        isLike: false,
    },
    {
        video:videos.video4,
        postProfile: Icons.profile,
        title: 'Rohit Sharma',
        followers: '785 Followers',
        likes: '876k',
        isLike: false,
    },
    {
        video:videos.video5,
        postProfile: Icons.profile,
        title: 'Lionel Messi',
        followers: '785 Followers',
        likes: '1.2M',
        isLike: false,
    },
    {
        video:videos.video6,
        postProfile: Icons.profile,
        title: 'MS Dhoni',
        followers: '785 Followers',
        likes: '56k',
        isLike: false,
    },
    {
        video:videos.video1,
        postProfile: Icons.profile,
        title: 'Cillian Murphy',
        followers: '785 Followers',
        likes: '90k',
        isLike: false,
    },
    {
        video:videos.video2,
        postProfile: Icons.profile,
        title: 'Henry Cavill',
        followers: '785 Followers',
        likes: '25k',
        isLike: false,
    },
    {
        video:videos.video3,
        postProfile: Icons.profile,
        title: 'Sachin Tendulkar',
        followers: '785 Followers',
        likes: '76k',
        isLike: false,
    },
];
